data:
    dataset: "human36m"
    dataset_path: "./data/data_3d_h36m.npz"
    dataset_path_train_2d: "./data/data_2d_h36m_gt_gmm.npz"
    dataset_path_test_2d: "./data/data_2d_h36m_cpn_ft_h36m_dbb_gmm.npz"
    num_joints: 17
    num_workers: 16

pretrain:
    batch_size: 16
    n_epochs: 1
    num_workers: 16

    gradient_clipping: 1.0
    weight_decay: 0.00000001
    learning_rate: 0.0001
    amp: False

    pretrain_model_root: "pretrained/"
    save_data_root: "mmdata2/"




model:
    hid_dim: 96
    emd_dim: 96
    coords_dim: [5,5]
    num_layer: 5
    n_head: 4
    dropout: 0.25
    n_pts: 17
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True
    var_type: fixedsmall
    pretrain_model_root: "pretrained/"

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.001
    num_diffusion_timesteps: 51

training:
    batch_size: 128
    n_epochs: 100
    num_workers: 16

testing:
    test_times: 1
    test_timesteps: 2
    test_num_diffusion_timesteps: 25

optim:
    decay: 60
    optimizer: "Adam"
    lr: 0.00002
    lr_gamma: 0.9
    eps: 0.00000001
    amsgrad: false
    grad_clip: 1.0




    
